### ISSUE TITLE
Test upgrade to 0.5.1

### ISSUE THREAD

**Issue by r-casula** [Aridhia-Open-Source/PHEMS_federated_node#64]
In our QC environment we are running 0.0.6 and with 0.5.1 come several breaking changes. We need to make sure that aside the annotation/labels missing all goes smoothly

**Comment by hepzibhafaustina** [comment]
Upgrade testing completed successfully. QC is now on 0.5.1 and all the endpoints results are as expected. [fnupgrade_20112024.docx](https://github.com/user-attachments/files/17829931/fnupgrade_20112024.docx)
